controller_list:
  - name: fake_arm_controller
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
  - name: fake_eef_controller
    joints:
      - pg70_finger_left_joint
      - pg70_finger_right_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: eef
    pose: gripper_open