# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_1_joint
    - arm_2_joint
    - arm_3_joint
    - arm_4_joint
    - arm_5_joint
    - arm_6_joint
    - pg70_finger_left_joint
    - pg70_finger_right_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
  - name: eef_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - pg70_finger_left_joint
      - pg70_finger_right_joint
arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_1_joint
    - arm_2_joint
    - arm_3_joint
    - arm_4_joint
    - arm_5_joint
    - arm_6_joint
  gains:
    arm_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_6_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
eef_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - pg70_finger_left_joint
    - pg70_finger_right_joint
  gains:
    pg70_finger_left_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    pg70_finger_right_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1


initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: eef
    pose: gripper_close